development:
  bucket: samsung-dev
  access_key_id: AKIAICFHBCFDDRL2PPBQ
  secret_access_key: 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
test:
  bucket: samsung-test
  access_key_id: AKIAICFHBCFDDRL2PPBQ
  secret_access_key: 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
production:
  bucket: samsung-pro
  access_key_id: AKIAICFHBCFDDRL2PPBQ
  secret_access_key: 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
